hyperfleet:
  applicationName: hyperfleet-operator

  namespace: argocd

  targetNamespace: hyperfleet

  project: default

  source:
    repoURL: https://github.com/willkutler/rosa-hyperfleet-api.git
    targetRevision: ROSAENG-65538
    path: hyperfleet-operator/charts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  helmValues:
    image:
      repository: quay.io/willkutler/hyperfleet-operator
      tag: "3448a2b"
      pullPolicy: Always

    replicaCount: 2

    serviceAccount:
      create: true
      name: hyperfleet-operator
      annotations: {}

    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
